baseurl: "/"
languageCode: "en-us"
title: "DraftLookHockey"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Tier One
      url: "/post/tierone/"
      weight: 2
    - name: Tier Two
      url: "/post/tiertwo/"
      weight: 3
    - name: Tier Three
      url: "/post/tierthree/"
      weight: 4
    - name: Tier Four
      url: "/post/tierfour/"
      weight: 5
    - name: Tier Five
      url: "/post/tierfive/"
      weight: 6
    - name: Links
      url: "/Links/"
      weight: 7

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Yihui Xie](https://yihui.org) 2017 -- 2020 | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"

markup:
  goldmark:
    renderer:
      unsafe: true
